### ISSUE TITLE
Ship first release

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/selinux#1]

**Comment by caniszczyk** [comment]
cc: @opencontainers/go-selinux-maintainers you're a live project now :)

**Comment by runcom** [comment]
Awesome, I'll work with the others to cut the first release

**Comment by cyphar** [comment]
@runcom Any update on this?

**Comment by runcom** [comment]
@cyphar I believe we're ok shipping first RC1 even if projects such as cri-o and docker and runc already moved to this library. I'm sending out a vote for RC1 if you all ok.

**Comment by runcom** [comment]
@cyphar https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/Cc6nsD1HIa4

**Comment by runcom** [comment]
RC1 went out

**Comment by rhatdan** [comment]
@caniszczyk Can I be made an Admin and get reviewer rights on this, since I am the biggest contributor.

**Comment by caniszczyk** [comment]
@rhatdan you should have reviewer rights

cc: @opencontainers/selinux-maintainers
