### ISSUE TITLE
Tag current master as v1.6.1

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/selinux#116]
Some changes went into master and are not yet tagged in a release; https://github.com/opencontainers/selinux/compare/v1.6.0...master

No major changes, but it'd be nice to have `go.mod` depend on a tagged version of willf/bitset;

- https://github.com/opencontainers/selinux/pull/113 Clarify documentation for Set{Task,Exec}Label
- https://github.com/opencontainers/selinux/pull/114 go.mod: update willf/bitset v1.1.11
- https://github.com/opencontainers/selinux/pull/115 travis: add go 1.15, rm unsupported versions

@rhatdan @kolyshkin @mrunalp ptal

**Comment by vrothberg** [comment]
SGTM

**Comment by AkihiroSuda** [comment]
@rhatdan PTAL?

**Comment by rhatdan** [comment]
Released v1.7.0
