### ISSUE TITLE
Request: remove "selinux" build tag

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/selinux#130]
@rhatdan 

Can we remove `selinux` build tag?

This package is matured and does not have any cgo dependency, so it seems safe to build-in the package by default.

The build tag seems introduced in the initial commit moby/moby@4c4356692580afb3971094e322aea64abe0e2500 (https://github.com/moby/moby/pull/4211).

**Comment by AkihiroSuda** [comment]
Related: https://github.com/opencontainers/runc/issues/2704 (Proposal: remove "apparmor" build tag)

**Comment by rhatdan** [comment]
Please open a PR to remove it.

**Comment by AkihiroSuda** [comment]
Sure, may I just remove the stub entirely? Or do we want to preserve the stub with "no_selinux" tag?

**Comment by rhatdan** [comment]
I would think just remove it entirely.  I don't believe it adds much size to an binary, so don't see much valure in the tag.

**Comment by rhatdan** [comment]
@thaJeztah @mrunalp @vrothberg @kolyshkin WDYT?

**Comment by thaJeztah** [comment]
Generally seems ok, I think most functions are already gated by a check if selinux is enabled; https://github.com/opencontainers/selinux/blob/824b4009894c1b48f5676131f5badf0176ba42f5/go-selinux/label/label_selinux.go#L31-L33

That said; please double check if there's code paths that were missed

**Comment by rhatdan** [comment]
Well sadly some people still disable SELinux, so these code paths should have been hit, if they were going to cause issue.  But it never hurts to check.

**Comment by thaJeztah** [comment]
True; was more thinking of distros without SELinux

**Comment by kolyshkin** [comment]
Makes total sense to me :+1:

**Comment by AkihiroSuda** [comment]
PR: https://github.com/opencontainers/selinux/pull/132

@rhatdan Could you release v1.8.0 with this?

**Comment by rhatdan** [comment]
@AkihiroSuda as soon as I get the second LGTM I will merge and cut a release.
