### ISSUE TITLE
Copyright is unclear

### ISSUE THREAD

**Issue by dimitar-dimitrow** [opencontainers/selinux#167]
Could you please clear up the copyright status? There is no copyright header in any code file and in the LICENCE it is stated as:

> Copyright {yyyy} {name of copyright owner}

**Comment by rhatdan** [comment]
Its licence is Apache License 2.0

opencontainers/selinux is licensed under the
Apache License 2.0

The copyright, I believe is owned by all of the contributors.

**Comment by thaJeztah** [comment]
I think to correctly apply the license, the repository needs to have

- a NOTICE file (which has the copyright holder)
- and/or license headers (similar to https://github.com/containerd/containerd/commit/b12c3215a0af92b9244b14c8555fc028b0d1d8c1)

I can have a look at adding those if I find some time
