### ISSUE TITLE
 Arguments validation about "InitLabels(options []string)"

### ISSUE THREAD

**Issue by miaoyq** [opencontainers/selinux#17]
Is a bad data for `options` in `InitLabels(options []string)` if the value is the form like `{"user:", "role:user_r", "type:", "level:s0:c1,c2"}`?  Test case does not contain this.

Hope to get help, thanks! : )

/cc @caniszczyk

**Comment by rhatdan** [comment]
user: and type: should be rejected yes.

**Comment by miaoyq** [comment]
@rhatdan thanks for the reply. : )
