### ISSUE TITLE
make getSELinuxfs() check default path first

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/selinux#23]
I noticed that [libselinux](https://github.com/SELinuxProject/selinux/tree/master/libselinux) implementation tries the default path (`/sys/fs/selinux`) first (checking its fstype and readonly flag), then the old default (`/selinux`), and only if that fails it goes on to parse `/proc/self/mountinfo` in order to find the selinux mount point. The relevant commit is https://github.com/SELinuxProject/selinux/commit/e3cab998b48ab

The implementation in this repo doesn't do that, it parses /proc/self/mountinfo right away (albeit once), the code is here:
https://github.com/opencontainers/selinux/blob/76b408a8e68e301b8245ba414ab600a0d1d797d9/go-selinux/selinux.go#L93

Maybe it makes sense to amend this function to try the default first (I guess there's no need to try the old default, no one uses it now). I would create a PR, but it will mess with https://github.com/opencontainers/selinux/pull/20 so I'm filing an issue instead.

**Comment by rhatdan** [comment]
Open a PR...

**Comment by kolyshkin** [comment]
> Open a PR...

I had the code ready some time ago, was too lazy then to add a unit test, which I have done now. @rhatdan PTAL

**Comment by kolyshkin** [comment]
Since https://github.com/opencontainers/selinux/pull/26 is now merged, this can be closed.
