### ISSUE TITLE
Please cut a semver release that includes the labels package

### ISSUE THREAD

**Issue by integrii** [opencontainers/selinux#47]
Go modules require that [semver is used](https://github.com/golang/go/issues/28931).  I need to rewrite a go module path to the labels package in this repo:

`replace github.com/opencontainers/runc/libcontainer/label => github.com/opencontainers/selinux/go-selinux/label v1.2`

However, version 1.2 is incompatible with go modules and I can't do this rewrite.  If I pin to you're 1.0.0 tag, the labels package appears to not exist yet, which also isn't going to work.

Here is the error go gives when I attempt to rewrite label package dependencies to your repository: `/Users/egreer200/git/kuberhealthy/pkg/go.mod:9: invalid module version github.com/opencontainers/selinux/go-selinux/label: no matching versions for query "v1.2"`

Also, just ot be sure, `github.com/opencontainers/runc/libcontainer/label` was moved to `github.com/opencontainers/selinux/go-selinux/label`, right?

**Comment by rhatdan** [comment]
This was done long ago.
