### ISSUE TITLE
Move container SELinux policy

### ISSUE THREAD

**Issue by mrunalp** [opencontainers/selinux#6]
@rhatdan @runcom We can move the SELinux policy for containers to this repo for a one stop for all things SELinux for containers.

**Comment by rhatdan** [comment]
Any chance we could rename the repo to be just selinux and not go-selinux and then make go-selinux a directory?  Seems weird to put container-selinux policy inside of a go-selinux repo.

selinux/policy
selinux/golang

Or something like that?

**Comment by mrunalp** [comment]
Yeah, agree.

**Comment by caniszczyk** [comment]
if the @opencontainers/go-selinux-maintainers agree I'm fine doing this

**Comment by runcom** [comment]
:+1:

**Comment by caniszczyk** [comment]
final call @opencontainers/go-selinux-maintainers on the project rename, if there are no issues I'm fine doing the rename

**Comment by mrunalp** [comment]
@caniszczyk Yeah, let's rename it.

**Comment by caniszczyk** [comment]
@mrunalp renamed

**Comment by mrunalp** [comment]
@caniszczyk Thanks!

**Comment by cpuguy83** [comment]
Wouldn't the selinux policy greatly depend on the base policy which may (or rather, does AFAICT) between distros?

**Comment by rhatdan** [comment]
The answer is yes, well somewhat anyways.
