### ISSUE TITLE
unix.SELINUX_MAGIC (untyped int constant 4185718668) overflows int32

### ISSUE THREAD

**Issue by dims** [opencontainers/selinux#73]
@kolyshkin the following change https://github.com/opencontainers/selinux/pull/64/commits/86a2c3f3bd5df7c6f96c072b51d515c29f04a143 seems to cause an issue in the kubernetes typecheck scripts. Please see the output in:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86975/pull-kubernetes-typecheck/1232997816310173697

The kubernetes PR where we are trying to update to newer selinux package is:
https://github.com/kubernetes/kubernetes/pull/86975#issuecomment-592043990

For the record the error is:
```
ERROR(linux/386,linux/arm) vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go:118:17: unix.SELINUX_MAGIC (untyped int constant 4185718668) overflows int32
exit status 1
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
```

**Comment by dims** [comment]
on arm and 386, `Statfs_t` seems to be `Type    int32`
- https://github.com/golang/sys/blob/master/unix/ztypes_linux_arm.go#L1430
- https://github.com/golang/sys/blob/master/unix/ztypes_linux_386.go#L1441

Is it possible to revert this change and make a fresh release for us to use?

**Comment by dims** [comment]
@saschagrunert beat me to it with a PR! thanks @saschagrunert and @mrunalp 

https://github.com/opencontainers/selinux/pull/71

**Comment by saschagrunert** [comment]
Hah, nice to see that we found the same issue. 🙂
