### ISSUE TITLE
Make recursive chcon threaded.

### ISSUE THREAD

**Issue by rhatdan** [opencontainers/selinux#84]
Currently chcon of large directories takes a very long time.  We have experimented with kicking off a thread for each directory and recusively calling chown, and have seen serious improvements in speed.
Up to 10 times faster

Here is my experimental code
https://github.com/rhatdan/tools/blob/master/chown.go

It would be nice to use this inside of the selinux library.

**Comment by kolyshkin** [comment]
Played a bit with it (before seeing @rhatdan code), didn't get 10x speedup but 3x is not bad, too, I guess. Please see #85.

**Comment by kolyshkin** [comment]
Fixed by https://github.com/opencontainers/selinux/pull/89
